### ISSUE TITLE
有几点实际使用中的疑问or bug

### ISSUE THREAD

**Issue by justmd5** [HanSon/speedy#5]
```php
public function permissions()
    {
        return $this->role->permissions();
    }
```
* 这个地方默认注册用户，因为没有角色，所以会报错，
* 是否可以考虑任何节点都没有的用户，进入admin直接跳转到站点首页呢。

## thanks

**Comment by Hanson** [comment]
是什么时候报错？如果有添加middleware的话，会判断是否存在role_id

**Comment by justmd5** [comment]
通过前台注册的用户，进入/admin 并不会分配任何角色，也就不会存在permissions，所以会报未定义错误。

**Comment by Hanson** [comment]
对于注册用户，一般业务逻辑是不允许进入管理后台的，这里我可以修改一下中间件，然后在登录成功的控制器加上中间件即可

**Comment by Hanson** [comment]
@justmd5 现在新版本已经分离出两个中间件，一个判断是否存在角色，一个判断权限，假若你的后台首页需要权限验证，可以把controller继承 `Hanson\Youzan\Http\Controllers\BaseController` 即可
